routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\MapController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AgentController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\DisputeController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\DocumentController;
use App\Http\Controllers\Admin\PeakHourController;
use App\Http\Controllers\Admin\ProviderController;
use App\Http\Controllers\Admin\PromocodeController;
use App\Http\Controllers\Admin\StatementController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\CustomPushController;
use App\Http\Controllers\Admin\GeoFencingController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\SettlementController;
use App\Http\Controllers\Admin\DisputeTypeController;
use App\Http\Controllers\Admin\ServiceTypeController;
use App\Http\Controllers\Admin\CancelReasonController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\FrontendSettingController;
use App\Http\Controllers\Admin\ProviderDocumentController;
use App\Http\Controllers\Admin\ServiceRentalHourController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes
Route::prefix('/')->group(function () {
    Route::get('/', [LoginController::class, 'showLoginForm']);
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('loginForm');
    Route::post('/login', [LoginController::class, 'login'])->name('login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
});

// Other Routes
Route::prefix('/')->middleware('auth:admin')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
    Route::view('translation', 'admin.translations')->name('translations');
    Route::view('telescope', 'admin.telescope')->name('telescope');

    // Dispatcher
    Route::get('/dispatcher', [HomeController::class, 'dispatcher'])->name('dispatcherDashboard');
    Route::get('/demoo', [ConfigController::class, 'demoo']);
    
    // Map
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/heatMap', [MapController::class, 'heatMap'])->name('map.heatMap');

    Route::get('/otherSettings', [HomeController::class, 'settings'])->name('settings.otherSettings');
    Route::get('/pushTest', [HomeController::class, 'pushtest']);
    
    // User Request
    // Route::get('/userRequest/{userRequest}/show', [HomeController::class, 'userRequest'])->name('userRequest.show');
    Route::get('requestHistory', [HomeController::class, 'requestHistory'])->name('request.history');
    Route::get('requestDetail/{userRequest}', [HomeController::class, 'requestDetail'])->name('request.detail');

    // Constants Config File
    Route::post('/settings/generalConfig', [ConfigController::class, 'generalConfig'])->name('settings.generalConfig');
    Route::post('/settings/saveSocialLinks', [ConfigController::class, 'saveSocialLinkSettings'])->name('settings.storeSocialLinks');
    Route::post('/settings/saveSocialConfig', [ConfigController::class, 'saveSocialConfig'])->name('settings.storeSocialConfig');
    Route::post('/settings/saveSearch', [ConfigController::class, 'saveSearch'])->name('settings.storeSearch');
    Route::post('/settings/saveApi', [ConfigController::class, 'saveApi'])->name('settings.storeApi');
    Route::post('/settings/saveEmail', [ConfigController::class, 'saveEmail'])->name('settings.storeEmail');
    Route::post('/settings/storePushNotification', [ConfigController::class, 'savePush'])->name('settings.storePushNotification');
    Route::post('/settings/saveOther', [ConfigController::class, 'saveOther'])->name('settings.storeOthers');

    // Frontend Settings File
    Route::get('/settings/frontend', [FrontendSettingController::class, 'index'])->name('settings.frontend.index');
    Route::post('/settings/frontend/top', [FrontendSettingController::class, 'headSetting'])->name('settings.frontend.headSetting');
    Route::post('/settings/frontend/steps', [FrontendSettingController::class, 'steps'])->name('settings.frontend.steps');
    Route::post('/settings/frontend/appDisplay', [FrontendSettingController::class, 'appDisplay'])->name('settings.frontend.appDisplay');

    // Database
    Route::get('tnc', [HomeController::class, 'tnc'])->name('settings.tnc');
    Route::post('/settings/tnc', [HomeController::class, 'saveTnc'])->name('settings.saveTnc');
    Route::get('privacy', [HomeController::class, 'privacy'])->name('settings.privacy');
    Route::post('/settings/privacyPolicy', [HomeController::class, 'savePrivacy'])->name('settings.savePrivacy');

    Route::get('/profileSettings', [HomeController::class, 'profileSettings'])->name('profileSettings');
    Route::post('/changePassword', [HomeController::class, 'changePassword'])->name('changePassword');
    Route::post('/updateProfile', [HomeController::class, 'updateProfile'])->name('updateProfile');
    Route::get('/language/{lang}', [HomeController::class, 'language'])->name('updateLanguage');
    

    // Statements
    Route::get('/statements/overall/{for?}/{id?}', [StatementController::class, 'index'])->name('statement.overall');
    Route::get('/statements/provider', [StatementController::class, 'providerStatements'])->name('statement.provider');
    Route::get('/statements/user', [StatementController::class, 'userStatements'])->name('statement.user');
    Route::get('/statements/agent', [StatementController::class, 'agentStatements'])->name('statement.agent');

    // Payment
    Route::get('/payment/history', [PaymentController::class, 'paymentHistory'])->name('payment.history');
    Route::get('/payment/setting', [PaymentController::class, 'paymentSetting'])->name('payment.setting');
    Route::post('/payment/setting', [PaymentController::class, 'savePaymentSetting'])->name('payment.saveSetting');
    Route::post('/payment/methodSetting', [PaymentController::class, 'savePaymentMethodSetting'])->name('payment.savePaymentMethodSetting');

    // Settlements - New Settlement Controller
    Route::get('settlements', [SettlementController::class, 'index'])->name('settlement.index');
    Route::get('settlements/create', [SettlementController::class, 'create'])->name('settlement.create');
    Route::post('settlements/store', [SettlementController::class, 'store'])->name('settlement.store');
    Route::get('/transactions', [PaymentController::class, 'allTransactions'])->name('settlement.allTransaction');

    // Ratings
    Route::get('/ratings', [HomeController::class, 'ratings'])->name('ratings');

    // Graphs
    Route::get('/getAdminCredits', [HomeController::class, 'getAdminCredits'])->name('getAdminCredits');
    Route::get('/getUserRequestStatus', [HomeController::class, 'getUserRequestStatus'])->name('getUserRequestStatus');

    // Handling Documents
    Route::get('/acceptDocument/{providerDocument}', [ProviderDocumentController::class, 'acceptDocument'])->name('acceptProviderDocument');
    Route::delete('/rejectDocument/{providerDocument}', [ProviderDocumentController::class, 'rejectDocument'])->name('rejectProviderDocument');

    // Handling Provider
    Route::put('/blockProvider/{provider}', [ProviderController::class, 'blockProvider'])->name('provider.blockProvider');
    Route::put('/approveProvider/{provider}', [ProviderController::class, 'approveProvider'])->name('provider.approveProvider');
    
    // Dispute Routes
    Route::resource('dispute', DisputeController::class)->only([
        'index', 'edit', 'update'
    ]);

    // Resource Route
    Route::resource('user', UserController::class);
    Route::resource('faq', FaqController::class);
    Route::resource('admin', AdminController::class);
    Route::resource('provider', ProviderController::class);
    Route::resource('agent', AgentController::class);
    Route::resource('role', RoleController::class);
    Route::resource('geoFencing', GeoFencingController::class);
    Route::resource('document', DocumentController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('disputeType', DisputeTypeController::class);
    Route::resource('serviceType', ServiceTypeController::class);
    Route::get('serviceType/{serviceType}/subServices', [ServiceTypeController::class, 'subServices'])->name('subServices');
    Route::resource('cancelReason', CancelReasonController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('peakHour', PeakHourController::class);
    Route::resource('notification', NotificationController::class);
    Route::resource('promocode', PromocodeController::class);
    Route::resource('customPush', CustomPushController::class);

    Route::resource('providerSettlement', SettlementController::class)->except([
        'create', 'store',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\Auth\LoginController;
use App\Http\Controllers\User\Auth\RegisterController;
use App\Http\Controllers\User\Auth\SocialAuthentication;
use App\Http\Controllers\User\ServiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/faq', [HomeController::class, 'faq'])->name('faq');
Route::get('/contactUs', [HomeController::class, 'contactUs'])->name('contactUs');
Route::get('/tnc', [HomeController::class, 'tnc'])->name('tnc');
Route::get('/privacyPolicy', [HomeController::class, 'privacy'])->name('privacy');

// Route::get('/blog', [HomeController::class, 'blog'])->name('blog');
// Route::get('/geoFence/{geoFencing}/serviceType/{serviceType}', [HomeController::class, 'service'])->name('geoFenceServices');
// Route::get('/getService/{serviceType}', [HomeController::class, 'getServiceAjax'])->name('getServiceAjax');

// Type hint this in controller
// Route::get('/blog/{blog}', [HomeController::class, 'showBlog'])->name('viewBlog');

// Authentication Routes
// Route::name('user.')->prefix('user/')->group(function () {

//     // Manual
//     Route::get('/login', [LoginController::class, 'showLoginForm'])->name('loginForm');
//     Route::post('/login', [LoginController::class, 'login'])->name('login');
//     Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('registrationForm');
//     Route::post('/register', [RegisterController::class, 'register'])->name('register');
//     Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
// });

// // Google
// Route::name('user.')->middleware('guest')->group(function() {
//     // Google
//     Route::get('/user/sign-up/google', [SocialAuthentication::class, 'googleLogin'])->name('google.registration');
//     Route::get('/user/sign-in/google', [SocialAuthentication::class, 'googleLogin'])->name('google.login');
//     Route::get('google/success', [SocialAuthentication::class, 'googleRedirect']);
// });

// // User Routes After Authentication
// Route::name('user.')->prefix('user/')->middleware('auth:web')->group(function() {
//     Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('home');
//     Route::get('{geoFence}/{serviceType}/checkout/', [ServiceController::class, 'serviceCheckout'])->name('serviceCheckout');
// });

app/Models/Document.php
<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Document extends Model
{
    use HasFactory, Searchable;

    protected $guarded = [];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'type',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at',
    ];

    /**
     * Scope a query to only include popular users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeVehicle($query)
    {
        return $query->where('type', 'VEHICLE');
    }

    /**
     * Scope a query to only include popular users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeDriver($query)
    {
        return $query->where('type', 'DRIVER');
    }

    public function providerdocuments()
    {
        return $this->hasOne('App\Models\ProviderDocument', 'document_id')->select(['url', 'status', 'document_id']);
    }
}

app/Http/Controllers/Admin/DocumentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\{
    StoreDocumentRequest, UpdateDocumentRequest
};

use Illuminate\Http\Request;

use App\Models\Document;

class DocumentController extends Controller
{
    public function __construct()
    {
        $this->middleware('demo')->only(['update', 'destroy']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('list documents', Document::class);
        $search = $request->get('search', '');

        $documents = Document::search($search)
            ->latest()
            ->paginate();
            
        return view('admin.document.index', compact('documents', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create documents', Document::class);
        return view('admin.document.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDocumentRequest $request)
    {
        $credentials = $request->validated();
        Document::create($credentials);

        return redirect()
            ->route('admin.document.index')
            ->with('success', __('crud.admin.documents.name')." ".__('crud.general.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        abort(403);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        return view('admin.document.edit', compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDocumentRequest $request, Document $document)
    {
        $this->authorize('view documents', $document);
        $credentials = $request->validated();

        $document->update($credentials);
        
        return redirect()
            ->route('admin.document.index')
            ->with('success', __('crud.admin.documents.name')." ".__('crud.general.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document)
    {
        $this->authorize('delete documents', $document);
        try {
            $document->delete();
        } catch (\Illuminate\Database\QueryException $e) {
            if($e->getCode() == 23000)
            {
                return redirect()
                    ->back()
                    ->withErrors(__('crud.general.integrity_violation'));
            }
            return redirect()
                ->back()
                ->withErrors(__('crud.general.not_done'));
        }

        return redirect()
            ->back()
            ->withSuccess(__('crud.general.deleted'));
    }
}

resources/views/admin/document/create.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.documents.create') }}
@endsection

@section('heading')
    {{ __('crud.admin.documents.create') }}
@endsection

@section('content')
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <x-form action="{{ route('admin.document.store') }}" method="post" has-file>
                @include('admin.document.form-inputs')
                
                <div class="flex justify-end">
                    <button type="submit" class="right-0 inline-block py-1 px-4 leading-loose bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg transition duration-200 text-sm" type="submit">Add {{ __('crud.admin.documents.name') }}</button>
                </div>
            </x-form>
        </div>
    </div>
@endsection

resources/views/admin/document/edit.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.documents.update') }}
@endsection

@section('heading')
    {{ __('crud.admin.documents.update') }}
@endsection

@section('content')
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <x-form action="{{ route('admin.document.update', $document) }}" method="put" has-file>
                @include('admin.document.form-inputs')
                
                <div class="flex justify-end">
                    <button type="submit" class="right-0 inline-block py-1 px-4 leading-loose bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg transition duration-200 text-sm" type="submit">Update {{ __('crud.admin.documents.name') }}</button>
                </div>
            </x-form>
        </div>
    </div>
@endsection

resources/views/admin/document/form-inputs.blade.php
@php 
    $editing = isset($document);
@endphp

<div class="flex flex-wrap -mx-4 -mb-4 md:mb-0">
    <x-inputs.text name="name" :label="__('crud.inputs.name')" value="{{ old('name', ($editing ? $document->name : '')) }}"></x-inputs.text>

    <x-inputs.select :label="__('crud.inputs.type')" name="type">
        <option {{ old('type', ($editing ? $document->type : '')) == "DRIVER" ? 'selected' : '' }} value="DRIVER">Driver</option>
        <option {{ old('type', ($editing ? $document->type : '')) == "VEHICLE" ? 'selected' : '' }} value="VEHICLE">Vehicle</option>
    </x-inputs.select>
    
    <x-inputs.status :label="__('crud.inputs.status')" name="status" status="{{ old('status', ($editing ? $document->status : '')) }}">
    </x-inputs.status>
</div>

resources/views/admin/document/index.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.documents.index') }}
@endsection

@section('heading')
    {{ __('crud.admin.documents.index') }}
@endsection

@section('content')
    <x-indexPageSearch :addBtnRoute="route('admin.document.create')" :addBtnText="__('crud.admin.documents.create')"></x-indexPageSearch>
    <div class="w-full overflow-hidden rounded-lg shadow-xs mb-6">
        <div class="w-full overflow-x-auto">
            <table class="w-full whitespace-no-wrap">
                <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="text-center px-4 py-3">{{ __('crud.inputs.SNo') }}</th>
                        <th class="text-center px-4 py-3">{{ __('crud.inputs.name') }}</th>
                        <th class="text-center px-4 py-3">{{ __('crud.inputs.type') }}</th>
                        <th class="text-center px-4 py-3">{{ __('crud.inputs.status') }}</th>
                        <th class="text-center px-4 py-3">{{ __('crud.general.actions') }}</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    {{-- Approved --}}
                    @forelse ($documents as $document)
                        <tr class="text-gray-700 dark:text-gray-400">
                            <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3">{{ $loop->index + 1 }}</td>
                            <td class="px-4 dark:text-gray-400 dark:bg-gray-800 py-3">
                                <div class="flex items-center text-sm">
                                    <p class="font-semibold text-gray-700 dark:text-gray-400">{{ $document->name }}</p>
                                </div>
                            </td>
                            <td class="px-4 dark:text-gray-400 dark:bg-gray-800 py-3 text-sm text-center">
                                {{ $document->type ?? '-'}}
                            </td>
                            <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3 text-sm">
                                <x-show-status :status="$document->status"></x-show-status>
                            </td>
                            <td>
                                <div class="flex items-center justify-center">
                                    <x-buttons.edit :link="route('admin.document.edit', $document)"></x-buttons.edit>
                                    <x-buttons.delete :link="route('admin.document.destroy', $document)"></x-buttons.delete>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td class="text-center dark:text-gray-400 dark:bg-gray-800 py-3 text-sm" colspan="10">
                                @lang('crud.general.not_found')
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        {{-- Pagination --}}
        <div class="">
            {!! $documents->links() !!}
        </div>
    </div>
@endsection

resources/views/admin/document/show.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.users.show') }}
@endsection

@section('content')
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ route('admin.user.index') }}" class="mr-2"><i class="icon ion-md-arrow-back"></i></a>
                        {{ __('crud.admin.users.show') }}
                    </h4>
    
                    <div class="mt-4 row">
                        <div class="col-lg-4 col-md-12">
                            <div class="text-center">
                                <img class="my-3" src="{{ $user->avatar ? asset('storage/'.$user->avatar) : asset('img/avatar.png') }}" style="object-fit: cover; width: 150px; height: 150px; border: 1px solid #ccc; border-radius: 50%;" />
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12 d-flex align-items-center">
                            <table wire:loading.remove wire:target="editMode" style="width: 100%;">
                                <tr class="view_td_container">
                                    <td class="view_td key">@lang('crud.admin.users.name')</td>
                                    <td class="view_td value">{{ $user->name ?? '-' }}</td>
                                    <td class="view_td key">@lang('crud.admin.users.email')</td>
                                    <td class="view_td value">{{ $user->email ?? '-' }}</td>
                                </tr>
                                <tr class="view_td_container">
                                    <td class="view_td key">@lang('crud.admin.users.phone')</td>
                                    <td class="view_td value">{{ $user->phone ?? '-' }}</td>
                                    <td class="view_td key">@lang('crud.roles.name')</td>
                                    <td class="view_td value">
                                        hdo
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection