routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\MapController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AgentController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\DisputeController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\DocumentController;
use App\Http\Controllers\Admin\PeakHourController;
use App\Http\Controllers\Admin\ProviderController;
use App\Http\Controllers\Admin\PromocodeController;
use App\Http\Controllers\Admin\StatementController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\CustomPushController;
use App\Http\Controllers\Admin\GeoFencingController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\SettlementController;
use App\Http\Controllers\Admin\DisputeTypeController;
use App\Http\Controllers\Admin\ServiceTypeController;
use App\Http\Controllers\Admin\CancelReasonController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\FrontendSettingController;
use App\Http\Controllers\Admin\ProviderDocumentController;
use App\Http\Controllers\Admin\ServiceRentalHourController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes
Route::prefix('/')->group(function () {
    Route::get('/', [LoginController::class, 'showLoginForm']);
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('loginForm');
    Route::post('/login', [LoginController::class, 'login'])->name('login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
});

// Other Routes
Route::prefix('/')->middleware('auth:admin')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
    Route::view('translation', 'admin.translations')->name('translations');
    Route::view('telescope', 'admin.telescope')->name('telescope');

    // Dispatcher
    Route::get('/dispatcher', [HomeController::class, 'dispatcher'])->name('dispatcherDashboard');
    Route::get('/demoo', [ConfigController::class, 'demoo']);
    
    // Map
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/heatMap', [MapController::class, 'heatMap'])->name('map.heatMap');

    Route::get('/otherSettings', [HomeController::class, 'settings'])->name('settings.otherSettings');
    Route::get('/pushTest', [HomeController::class, 'pushtest']);
    
    // User Request
    // Route::get('/userRequest/{userRequest}/show', [HomeController::class, 'userRequest'])->name('userRequest.show');
    Route::get('requestHistory', [HomeController::class, 'requestHistory'])->name('request.history');
    Route::get('requestDetail/{userRequest}', [HomeController::class, 'requestDetail'])->name('request.detail');

    // Constants Config File
    Route::post('/settings/generalConfig', [ConfigController::class, 'generalConfig'])->name('settings.generalConfig');
    Route::post('/settings/saveSocialLinks', [ConfigController::class, 'saveSocialLinkSettings'])->name('settings.storeSocialLinks');
    Route::post('/settings/saveSocialConfig', [ConfigController::class, 'saveSocialConfig'])->name('settings.storeSocialConfig');
    Route::post('/settings/saveSearch', [ConfigController::class, 'saveSearch'])->name('settings.storeSearch');
    Route::post('/settings/saveApi', [ConfigController::class, 'saveApi'])->name('settings.storeApi');
    Route::post('/settings/saveEmail', [ConfigController::class, 'saveEmail'])->name('settings.storeEmail');
    Route::post('/settings/storePushNotification', [ConfigController::class, 'savePush'])->name('settings.storePushNotification');
    Route::post('/settings/saveOther', [ConfigController::class, 'saveOther'])->name('settings.storeOthers');

    // Frontend Settings File
    Route::get('/settings/frontend', [FrontendSettingController::class, 'index'])->name('settings.frontend.index');
    Route::post('/settings/frontend/top', [FrontendSettingController::class, 'headSetting'])->name('settings.frontend.headSetting');
    Route::post('/settings/frontend/steps', [FrontendSettingController::class, 'steps'])->name('settings.frontend.steps');
    Route::post('/settings/frontend/appDisplay', [FrontendSettingController::class, 'appDisplay'])->name('settings.frontend.appDisplay');

    // Database
    Route::get('tnc', [HomeController::class, 'tnc'])->name('settings.tnc');
    Route::post('/settings/tnc', [HomeController::class, 'saveTnc'])->name('settings.saveTnc');
    Route::get('privacy', [HomeController::class, 'privacy'])->name('settings.privacy');
    Route::post('/settings/privacyPolicy', [HomeController::class, 'savePrivacy'])->name('settings.savePrivacy');

    Route::get('/profileSettings', [HomeController::class, 'profileSettings'])->name('profileSettings');
    Route::post('/changePassword', [HomeController::class, 'changePassword'])->name('changePassword');
    Route::post('/updateProfile', [HomeController::class, 'updateProfile'])->name('updateProfile');
    Route::get('/language/{lang}', [HomeController::class, 'language'])->name('updateLanguage');
    

    // Statements
    Route::get('/statements/overall/{for?}/{id?}', [StatementController::class, 'index'])->name('statement.overall');
    Route::get('/statements/provider', [StatementController::class, 'providerStatements'])->name('statement.provider');
    Route::get('/statements/user', [StatementController::class, 'userStatements'])->name('statement.user');
    Route::get('/statements/agent', [StatementController::class, 'agentStatements'])->name('statement.agent');

    // Payment
    Route::get('/payment/history', [PaymentController::class, 'paymentHistory'])->name('payment.history');
    Route::get('/payment/setting', [PaymentController::class, 'paymentSetting'])->name('payment.setting');
    Route::post('/payment/setting', [PaymentController::class, 'savePaymentSetting'])->name('payment.saveSetting');
    Route::post('/payment/methodSetting', [PaymentController::class, 'savePaymentMethodSetting'])->name('payment.savePaymentMethodSetting');

    // Settlements - New Settlement Controller
    Route::get('settlements', [SettlementController::class, 'index'])->name('settlement.index');
    Route::get('settlements/create', [SettlementController::class, 'create'])->name('settlement.create');
    Route::post('settlements/store', [SettlementController::class, 'store'])->name('settlement.store');
    Route::get('/transactions', [PaymentController::class, 'allTransactions'])->name('settlement.allTransaction');

    // Ratings
    Route::get('/ratings', [HomeController::class, 'ratings'])->name('ratings');

    // Graphs
    Route::get('/getAdminCredits', [HomeController::class, 'getAdminCredits'])->name('getAdminCredits');
    Route::get('/getUserRequestStatus', [HomeController::class, 'getUserRequestStatus'])->name('getUserRequestStatus');

    // Handling Documents
    Route::get('/acceptDocument/{providerDocument}', [ProviderDocumentController::class, 'acceptDocument'])->name('acceptProviderDocument');
    Route::delete('/rejectDocument/{providerDocument}', [ProviderDocumentController::class, 'rejectDocument'])->name('rejectProviderDocument');

    // Handling Provider
    Route::put('/blockProvider/{provider}', [ProviderController::class, 'blockProvider'])->name('provider.blockProvider');
    Route::put('/approveProvider/{provider}', [ProviderController::class, 'approveProvider'])->name('provider.approveProvider');
    
    // Dispute Routes
    Route::resource('dispute', DisputeController::class)->only([
        'index', 'edit', 'update'
    ]);

    // Resource Route
    Route::resource('user', UserController::class);
    Route::resource('faq', FaqController::class);
    Route::resource('admin', AdminController::class);
    Route::resource('provider', ProviderController::class);
    Route::resource('agent', AgentController::class);
    Route::resource('role', RoleController::class);
    Route::resource('geoFencing', GeoFencingController::class);
    Route::resource('document', DocumentController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('disputeType', DisputeTypeController::class);
    Route::resource('serviceType', ServiceTypeController::class);
    Route::get('serviceType/{serviceType}/subServices', [ServiceTypeController::class, 'subServices'])->name('subServices');
    Route::resource('cancelReason', CancelReasonController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('peakHour', PeakHourController::class);
    Route::resource('notification', NotificationController::class);
    Route::resource('promocode', PromocodeController::class);
    Route::resource('customPush', CustomPushController::class);

    Route::resource('providerSettlement', SettlementController::class)->except([
        'create', 'store',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\Auth\LoginController;
use App\Http\Controllers\User\Auth\RegisterController;
use App\Http\Controllers\User\Auth\SocialAuthentication;
use App\Http\Controllers\User\ServiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/faq', [HomeController::class, 'faq'])->name('faq');
Route::get('/contactUs', [HomeController::class, 'contactUs'])->name('contactUs');
Route::get('/tnc', [HomeController::class, 'tnc'])->name('tnc');
Route::get('/privacyPolicy', [HomeController::class, 'privacy'])->name('privacy');

// Route::get('/blog', [HomeController::class, 'blog'])->name('blog');
// Route::get('/geoFence/{geoFencing}/serviceType/{serviceType}', [HomeController::class, 'service'])->name('geoFenceServices');
// Route::get('/getService/{serviceType}', [HomeController::class, 'getServiceAjax'])->name('getServiceAjax');

// Type hint this in controller
// Route::get('/blog/{blog}', [HomeController::class, 'showBlog'])->name('viewBlog');

// Authentication Routes
// Route::name('user.')->prefix('user/')->group(function () {

//     // Manual
//     Route::get('/login', [LoginController::class, 'showLoginForm'])->name('loginForm');
//     Route::post('/login', [LoginController::class, 'login'])->name('login');
//     Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('registrationForm');
//     Route::post('/register', [RegisterController::class, 'register'])->name('register');
//     Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
// });

// // Google
// Route::name('user.')->middleware('guest')->group(function() {
//     // Google
//     Route::get('/user/sign-up/google', [SocialAuthentication::class, 'googleLogin'])->name('google.registration');
//     Route::get('/user/sign-in/google', [SocialAuthentication::class, 'googleLogin'])->name('google.login');
//     Route::get('google/success', [SocialAuthentication::class, 'googleRedirect']);
// });

// // User Routes After Authentication
// Route::name('user.')->prefix('user/')->middleware('auth:web')->group(function() {
//     Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('home');
//     Route::get('{geoFence}/{serviceType}/checkout/', [ServiceController::class, 'serviceCheckout'])->name('serviceCheckout');
// });

app/Models/GeoFencing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Scopes\Searchable;

class GeoFencing extends Model
{
    use HasFactory, SoftDeletes, Searchable;

    protected $guarded = [];

    public function serviceType()
    {
        return $this->belongsToMany(ServiceType::class, 'service_type_geo_fencings');
    }
        /**
     * ServiceType Model Linked
     */
    public function service_geo_fencing()
    {
        return $this->hasOne('App\Models\ServiceTypeGeoFencing', 'geo_fencing_id');
    }
}

app/Http/Controllers/Admin/GeoFencingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\GeoFencing;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreGeoFencingRequest;
use App\Http\Requests\Admin\UpdateGeoFencingRequest;

class GeoFencingController extends Controller
{
    public function __construct()
    {
        $this->middleware('demo')->only(['update', 'destroy']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('list geoFences', GeoFencing::class);
        $search = $request->get('search', '');

        $geoFencings = GeoFencing::search($search)
            ->latest()
            ->paginate();
        return view('admin.geoFencing.index', compact('geoFencings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create geoFences', GeoFencing::class);
        return view('admin.geoFencing.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreGeoFencingRequest $request)
    {
        $credentials = $request->all();
        GeoFencing::create($credentials);

        return redirect()
            ->route('admin.geoFencing.index')
            ->with('success', __('crud.admin.geoFencings.name')." ".__('crud.general.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(GeoFencing $geoFencing)
    {
        $this->authorize('view geoFences', $geoFencing);
        return view('admin.geoFencing.edit', compact('geoFencing'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateGeoFencingRequest $request, GeoFencing $geoFencing)
    {
        $credentials = $request->all();
        $geoFencing->update($credentials);

        return redirect()
            ->route('admin.geoFencing.index')
            ->with('success', __('crud.admin.geoFencings.name')." ".__('crud.general.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(GeoFencing $geoFencing)
    {
        $this->authorize('delete geoFences', $geoFencing);
        try {
            $geoFencing->delete();
        } catch (\Illuminate\Database\QueryException $e) {
            if($e->getCode() == 23000)
            {
                return redirect()
                    ->back()
                    ->withErrors(__('crud.general.integrity_violation'));
            }
            return redirect()
                ->back()
                ->withErrors(__('crud.general.not_done'));
        }

        return redirect()
            ->back()
            ->withSuccess(__('crud.general.deleted'));
    }
}

resources/views/admin/geoFencing/create.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.geoFencings.create') }}
@endsection

@section('heading')
    {{ __('crud.admin.geoFencings.create') }}
@endsection

@section('content')
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <form class="form-horizontal" action="{{route('admin.geoFencing.store')}}" method="POST" enctype="multipart/form-data" role="form">
                {{ csrf_field() }}
                <x-inputs.text space="mb:w-full" :label="__('crud.inputs.city_name')" name="city_name" space="w-full" value="{{ old('city_name') }}"></x-inputs.text>

                
                <div class="w-full px-4 mb-4 md:mb-0">
                    <div class="mb-6">
                        <x-inputs.partials.label name="picture" :label="__('crud.admin.geoFencings.draw')"></x-inputs.partials.label>
                        <div id="map"></div>
                        <input type="hidden" name="ranges" class="ranges" value="">
                    </div>
                </div>
            
                <button id="clear" type="submit" class="right-0 inline-block py-1 px-4 leading-loose bg-red-500 hover:bg-red-600 text-white font-semibold rounded-lg transition duration-200 text-sm" type="submit">
                    Click here to clear map
                </button>
                <button type="submit" class="right-0 inline-block py-1 px-4 leading-loose bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg transition duration-200 text-sm" type="submit">
                    {{ __('crud.general.add') }} {{ __('crud.admin.geoFencings.name') }}
                </button>
            </form>
        </div>
    </div>
@endsection

@push('endScripts')

    <script src="https://maps.googleapis.com/maps/api/js?key={{ config('constants.map_key') }}&libraries=places,drawing&callback=initMap" async defer></script>
    <script>
        var map;
        var polygon;
        var input = document.getElementById('pac-input');
        var s_latitude = document.getElementById('latitude');
        var s_longitude = document.getElementById('longitude');
        var s_address = document.getElementById('address');
        var arr = [];
        var selectedShape;

        var old_latlng = new Array();
        var markers = new Array();

        var OldPath = JSON.parse($('input.ranges').val());

        function initMap() {
            var userLocation = new google.maps.LatLng(0.0236, 37.9062);
            const searchBox = new google.maps.places.SearchBox(city_name);

            map = new google.maps.Map(document.getElementById('map'), {
                center: userLocation,
                zoom: 15,
            });

            map.addListener("bounds_changed", () => {
                searchBox.setBounds(map.getBounds());
            });

            let markers = [];
            
            searchBox.addListener("places_changed", () => {
                const places = searchBox.getPlaces();

                if (places.length == 0) {
                    return;
                }
            
                // Clear out the old markers.
                markers.forEach((marker) => {
                    marker.setMap(null);
                });
                markers = [];
                
                // For each place, get the icon, name and location.
                const bounds = new google.maps.LatLngBounds();

                places.forEach((place) => {
                    if (!place.geometry || !place.geometry.location) {
                        firstCoordinates = null;
                        console.log("Returned place contains no geometry");
                        return;
                    }

                    firstCoordinates = place.geometry.location.lat() + ',' + place.geometry.location.lng();
                
                    const icon = {
                        url: place.icon,
                        size: new google.maps.Size(71, 71),
                        origin: new google.maps.Point(0, 0),
                        anchor: new google.maps.Point(17, 34),
                        scaledSize: new google.maps.Size(25, 25),
                    };
                
                    // Create a marker for each place.
                    markers.push(
                        new google.maps.Marker({
                            map,
                            icon,
                            title: place.name,
                            position: place.geometry.location,
                        })
                    );

                    if (place.geometry.viewport) {
                        // Only geocodes have viewport.
                        bounds.union(place.geometry.viewport);
                    } else {
                        bounds.extend(place.geometry.location);
                    }
                });

                map.fitBounds(bounds);
            });


            var drawingManager = new google.maps.drawing.DrawingManager({
                drawingMode: google.maps.drawing.OverlayType.POLYGON,
                drawingControl: true,
                drawingControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER,
                    drawingModes: [google.maps.drawing.OverlayType.POLYGON]
                },
                polygonOptions: {
                    editable: true, 
                    draggable: true,
                    fillColor: '#ff0000', 
                    strokeColor: '#ff0000', 
                    strokeWeight: 1
                }
            });
            drawingManager.setMap(map);

            google.maps.event.addListener(drawingManager, 'overlaycomplete', function(e){
                var bounds = [];
                var layer_bounds = [];
                var newShape = e.overlay;
                if (e.type == google.maps.drawing.OverlayType.POLYGON) {
                    var locations = e.overlay.getPath().getArray();
                    arr.push(e);
                    $.each(locations, function(index, value){
                        var markerLat = (value.lat()).toFixed(6);
                        var markerLng = (value.lng()).toFixed(6);
                        layer_bounds.push(new google.maps.LatLng((value.lat()).toFixed(6), (value.lng()).toFixed(6)));
                        json = {
                            'lat': markerLat,
                            'lng': markerLng
                        };
                        bounds.push(json);                  
                    });
                    $('input.ranges').val(JSON.stringify(bounds));

                    overlayClickListener(e.overlay);
                    drawingManager.setOptions({drawingMode:null,drawingControl:false});
                    setSelection(newShape);
                }
            });

            $(document).on('click', '#clear', function(ev) {
                drawingManager.setMap(map);
                polygon.setMap(null);
                deleteSelectedShape();
                $('input.ranges').val('');
                ev.preventDefault();
                return false;
            });

            var old_polygon = [];

            $(OldPath).each(function(index, value){
                old_polygon.push(new google.maps.LatLng(value.lat, value.lng));
                old_latlng.push(new google.maps.LatLng(value.lat, value.lng));
            });
                
            polygon = new google.maps.Polygon({
                path: old_polygon,
                strokeColor: "#ff0000",
                strokeOpacity: 0.8,
                // strokeWeight: 1,
                fillColor: "#ff0000",
                fillOpacity: 0.3,
                editable: true,
                draggable: true,
            });
            
            polygon.setMap(map);
        }

        function createMarker(markerOptions) {
            var marker = new google.maps.Marker(markerOptions);
            markers.push(marker);
            old_latlng.push(marker.getPosition());
            return marker;
        }

        function overlayClickListener(overlay) {
            google.maps.event.addListener(overlay, "mouseup", function(event){
                var arr_loc = [];
                var locations = overlay.getPath().getArray();
                $.each(locations, function(index, value){
                    var locLat = (value.lat()).toFixed(6);
                    var locLng = (value.lng()).toFixed(6);
                    ltlg = {
                        'lat': locLat,
                        'lng': locLng
                    };
                    arr_loc.push(ltlg);                 
                });
                $('input.ranges').val(JSON.stringify(arr_loc));
            });
        }

        function setSelection (shape) {
            if (shape.type == 'polygon') {
                clearSelection();
                shape.setEditable(true);
            }
            selectedShape = shape;
        }

        function clearSelection () {
            if (selectedShape) {
                console.log(selectedShape.type);
                if (selectedShape.type == 'polygon') {
                    selectedShape.setEditable(false);
                }
                
                selectedShape = null;
            }
        }

        function deleteSelectedShape () {
            if (selectedShape) {
                $('input.ranges').val('');
                selectedShape.setMap(null);
            }
        }
    </script>

    <style type="text/css">
        #map {
            height: 100%;
            min-height: 400px;
        }

        .controls {
            border: 1px solid transparent;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            height: 32px;
            outline: none;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
            margin-bottom: 10px;
        }

        #pac-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 100%;
        }

        #bar {
            width: 240px;
            background-color: rgba(255, 255, 255, 0.75);
            margin: 8px;
            padding: 4px;
            border-radius: 4px;
        }
    </style>
@endpush

resources/views/admin/geoFencing/index.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.geoFencings.index') }}
@endsection

@section('heading')
    {{ __('crud.admin.geoFencings.index') }}
@endsection

@section('content')
    <x-indexPageSearch :addBtnRoute="route('admin.geoFencing.create')" :addBtnText="__('crud.admin.geoFencings.create')"></x-indexPageSearch>
    <div class="w-full overflow-hidden rounded-lg shadow-xs mb-6">
        <div class="w-full overflow-x-auto">
            <table class="w-full whitespace-no-wrap">
                <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                        <th class="text-center px-4 py-3">{{ __('crud.inputs.SNo') }}</th>
                        <th class="text-center px-4 py-3">{{ __('crud.inputs.city') }}</th>
                        <th class="text-center px-4 py-3">{{ __('crud.general.actions') }}</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                    {{-- Approved --}}
                    @forelse ($geoFencings as $geoFencing)
                        <tr class="text-gray-700 dark:text-gray-400">
                            <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3">{{ $loop->index + 1 }}</td>
                            <td class="px-4 dark:text-gray-400 dark:bg-gray-800 py-3 text-sm text-center">
                                {{ $geoFencing->city_name }}
                            </td>
                            <td>
                                <div class="flex items-center justify-center">
                                    <x-buttons.edit :link="route('admin.geoFencing.edit', $geoFencing)"></x-buttons.edit>
                                    <x-buttons.delete :link="route('admin.geoFencing.destroy', $geoFencing)"></x-buttons.delete>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td class="text-center dark:bg-gray-800 py-3 text-sm dark:text-gray-400" colspan="6">
                                @lang('crud.general.not_found')
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        {{-- Pagination --}}
        <div class="">
            {!! $geoFencings->links() !!}
        </div>
    </div>
@endsection