routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\MapController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AgentController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\DisputeController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\DocumentController;
use App\Http\Controllers\Admin\PeakHourController;
use App\Http\Controllers\Admin\ProviderController;
use App\Http\Controllers\Admin\PromocodeController;
use App\Http\Controllers\Admin\StatementController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\CustomPushController;
use App\Http\Controllers\Admin\GeoFencingController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\SettlementController;
use App\Http\Controllers\Admin\DisputeTypeController;
use App\Http\Controllers\Admin\ServiceTypeController;
use App\Http\Controllers\Admin\CancelReasonController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\FrontendSettingController;
use App\Http\Controllers\Admin\ProviderDocumentController;
use App\Http\Controllers\Admin\ServiceRentalHourController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication Routes
Route::prefix('/')->group(function () {
    Route::get('/', [LoginController::class, 'showLoginForm']);
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('loginForm');
    Route::post('/login', [LoginController::class, 'login'])->name('login');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
});

// Other Routes
Route::prefix('/')->middleware('auth:admin')->group(function () {
    Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
    Route::view('translation', 'admin.translations')->name('translations');
    Route::view('telescope', 'admin.telescope')->name('telescope');

    // Dispatcher
    Route::get('/dispatcher', [HomeController::class, 'dispatcher'])->name('dispatcherDashboard');
    Route::get('/demoo', [ConfigController::class, 'demoo']);
    
    // Map
    Route::get('/map', [MapController::class, 'index'])->name('map.index');
    Route::get('/heatMap', [MapController::class, 'heatMap'])->name('map.heatMap');

    Route::get('/otherSettings', [HomeController::class, 'settings'])->name('settings.otherSettings');
    Route::get('/pushTest', [HomeController::class, 'pushtest']);
    
    // User Request
    // Route::get('/userRequest/{userRequest}/show', [HomeController::class, 'userRequest'])->name('userRequest.show');
    Route::get('requestHistory', [HomeController::class, 'requestHistory'])->name('request.history');
    Route::get('requestDetail/{userRequest}', [HomeController::class, 'requestDetail'])->name('request.detail');

    // Constants Config File
    Route::post('/settings/generalConfig', [ConfigController::class, 'generalConfig'])->name('settings.generalConfig');
    Route::post('/settings/saveSocialLinks', [ConfigController::class, 'saveSocialLinkSettings'])->name('settings.storeSocialLinks');
    Route::post('/settings/saveSocialConfig', [ConfigController::class, 'saveSocialConfig'])->name('settings.storeSocialConfig');
    Route::post('/settings/saveSearch', [ConfigController::class, 'saveSearch'])->name('settings.storeSearch');
    Route::post('/settings/saveApi', [ConfigController::class, 'saveApi'])->name('settings.storeApi');
    Route::post('/settings/saveEmail', [ConfigController::class, 'saveEmail'])->name('settings.storeEmail');
    Route::post('/settings/storePushNotification', [ConfigController::class, 'savePush'])->name('settings.storePushNotification');
    Route::post('/settings/saveOther', [ConfigController::class, 'saveOther'])->name('settings.storeOthers');

    // Frontend Settings File
    Route::get('/settings/frontend', [FrontendSettingController::class, 'index'])->name('settings.frontend.index');
    Route::post('/settings/frontend/top', [FrontendSettingController::class, 'headSetting'])->name('settings.frontend.headSetting');
    Route::post('/settings/frontend/steps', [FrontendSettingController::class, 'steps'])->name('settings.frontend.steps');
    Route::post('/settings/frontend/appDisplay', [FrontendSettingController::class, 'appDisplay'])->name('settings.frontend.appDisplay');

    // Database
    Route::get('tnc', [HomeController::class, 'tnc'])->name('settings.tnc');
    Route::post('/settings/tnc', [HomeController::class, 'saveTnc'])->name('settings.saveTnc');
    Route::get('privacy', [HomeController::class, 'privacy'])->name('settings.privacy');
    Route::post('/settings/privacyPolicy', [HomeController::class, 'savePrivacy'])->name('settings.savePrivacy');

    Route::get('/profileSettings', [HomeController::class, 'profileSettings'])->name('profileSettings');
    Route::post('/changePassword', [HomeController::class, 'changePassword'])->name('changePassword');
    Route::post('/updateProfile', [HomeController::class, 'updateProfile'])->name('updateProfile');
    Route::get('/language/{lang}', [HomeController::class, 'language'])->name('updateLanguage');
    

    // Statements
    Route::get('/statements/overall/{for?}/{id?}', [StatementController::class, 'index'])->name('statement.overall');
    Route::get('/statements/provider', [StatementController::class, 'providerStatements'])->name('statement.provider');
    Route::get('/statements/user', [StatementController::class, 'userStatements'])->name('statement.user');
    Route::get('/statements/agent', [StatementController::class, 'agentStatements'])->name('statement.agent');

    // Payment
    Route::get('/payment/history', [PaymentController::class, 'paymentHistory'])->name('payment.history');
    Route::get('/payment/setting', [PaymentController::class, 'paymentSetting'])->name('payment.setting');
    Route::post('/payment/setting', [PaymentController::class, 'savePaymentSetting'])->name('payment.saveSetting');
    Route::post('/payment/methodSetting', [PaymentController::class, 'savePaymentMethodSetting'])->name('payment.savePaymentMethodSetting');

    // Settlements - New Settlement Controller
    Route::get('settlements', [SettlementController::class, 'index'])->name('settlement.index');
    Route::get('settlements/create', [SettlementController::class, 'create'])->name('settlement.create');
    Route::post('settlements/store', [SettlementController::class, 'store'])->name('settlement.store');
    Route::get('/transactions', [PaymentController::class, 'allTransactions'])->name('settlement.allTransaction');

    // Ratings
    Route::get('/ratings', [HomeController::class, 'ratings'])->name('ratings');

    // Graphs
    Route::get('/getAdminCredits', [HomeController::class, 'getAdminCredits'])->name('getAdminCredits');
    Route::get('/getUserRequestStatus', [HomeController::class, 'getUserRequestStatus'])->name('getUserRequestStatus');

    // Handling Documents
    Route::get('/acceptDocument/{providerDocument}', [ProviderDocumentController::class, 'acceptDocument'])->name('acceptProviderDocument');
    Route::delete('/rejectDocument/{providerDocument}', [ProviderDocumentController::class, 'rejectDocument'])->name('rejectProviderDocument');

    // Handling Provider
    Route::put('/blockProvider/{provider}', [ProviderController::class, 'blockProvider'])->name('provider.blockProvider');
    Route::put('/approveProvider/{provider}', [ProviderController::class, 'approveProvider'])->name('provider.approveProvider');
    
    // Dispute Routes
    Route::resource('dispute', DisputeController::class)->only([
        'index', 'edit', 'update'
    ]);

    // Resource Route
    Route::resource('user', UserController::class);
    Route::resource('faq', FaqController::class);
    Route::resource('admin', AdminController::class);
    Route::resource('provider', ProviderController::class);
    Route::resource('agent', AgentController::class);
    Route::resource('role', RoleController::class);
    Route::resource('geoFencing', GeoFencingController::class);
    Route::resource('document', DocumentController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('disputeType', DisputeTypeController::class);
    Route::resource('serviceType', ServiceTypeController::class);
    Route::get('serviceType/{serviceType}/subServices', [ServiceTypeController::class, 'subServices'])->name('subServices');
    Route::resource('cancelReason', CancelReasonController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('peakHour', PeakHourController::class);
    Route::resource('notification', NotificationController::class);
    Route::resource('promocode', PromocodeController::class);
    Route::resource('customPush', CustomPushController::class);

    Route::resource('providerSettlement', SettlementController::class)->except([
        'create', 'store',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\Auth\LoginController;
use App\Http\Controllers\User\Auth\RegisterController;
use App\Http\Controllers\User\Auth\SocialAuthentication;
use App\Http\Controllers\User\ServiceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/faq', [HomeController::class, 'faq'])->name('faq');
Route::get('/contactUs', [HomeController::class, 'contactUs'])->name('contactUs');
Route::get('/tnc', [HomeController::class, 'tnc'])->name('tnc');
Route::get('/privacyPolicy', [HomeController::class, 'privacy'])->name('privacy');

// Route::get('/blog', [HomeController::class, 'blog'])->name('blog');
// Route::get('/geoFence/{geoFencing}/serviceType/{serviceType}', [HomeController::class, 'service'])->name('geoFenceServices');
// Route::get('/getService/{serviceType}', [HomeController::class, 'getServiceAjax'])->name('getServiceAjax');

// Type hint this in controller
// Route::get('/blog/{blog}', [HomeController::class, 'showBlog'])->name('viewBlog');

// Authentication Routes
// Route::name('user.')->prefix('user/')->group(function () {

//     // Manual
//     Route::get('/login', [LoginController::class, 'showLoginForm'])->name('loginForm');
//     Route::post('/login', [LoginController::class, 'login'])->name('login');
//     Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('registrationForm');
//     Route::post('/register', [RegisterController::class, 'register'])->name('register');
//     Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
// });

// // Google
// Route::name('user.')->middleware('guest')->group(function() {
//     // Google
//     Route::get('/user/sign-up/google', [SocialAuthentication::class, 'googleLogin'])->name('google.registration');
//     Route::get('/user/sign-in/google', [SocialAuthentication::class, 'googleLogin'])->name('google.login');
//     Route::get('google/success', [SocialAuthentication::class, 'googleRedirect']);
// });

// // User Routes After Authentication
// Route::name('user.')->prefix('user/')->middleware('auth:web')->group(function() {
//     Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('home');
//     Route::get('{geoFence}/{serviceType}/checkout/', [ServiceController::class, 'serviceCheckout'])->name('serviceCheckout');
// });

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreUserRequest;
use App\Http\Requests\Admin\UpdateUserRequest;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

use App\Models\User;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('demo')->only(['update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('list users');

        $search = $request->get('search', '');

        $users = User::search($search)
            ->latest()
            ->paginate();

        return view('admin.user.index', compact('users', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create users', User::class);

        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        $this->authorize('create users', User::class);

        $credentials = $request->validated();
        $credentials['password'] = Hash::make($request['password']);

        if ($request->hasFile('avatar')) {
            $credentials['avatar'] = $request->file('avatar')->store('public/user/avatars');
        }

        User::create($credentials);
        
        return redirect()
            ->route('admin.user.index')
            ->with('success', __('crud.admin.users.name')." ".__('crud.general.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        // $this->authorize('view users', $user);
        abort(404);
        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('view users', $user);
        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $this->authorize('update users', User::class);
        
        $credentials = $request->validated();
        if ($request->hasFile('avatar')) {
            if ($user->avatar) {
                Storage::delete($user->avatar);
            }

            $credentials['avatar'] = $request->file('avatar')->store('public/user/avatars');
        }
        
        $user->update($credentials);

        return redirect()
            ->route('admin.user.index')
            ->with('success', __('crud.admin.users.name')." ".__('crud.general.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete users', $user);

        try {
            $avatar = $user->avatar ? $user->avatar : NULL;
            $user->mobile = $user->mobile.'-'.uniqid();
            $user->email = $user->email.'-'.uniqid();
            $user->social_unique_id = $user->social_unique_id.'-'.uniqid();
            $user->save();
            $user->delete();

            if($avatar) {
                Storage::delete($user->avatar);
            }
        } catch (\Illuminate\Database\QueryException $e) {
            if($e->getCode() == 23000)
            {
                return redirect()
                    ->back()
                    ->withErrors(__('crud.general.integrity_violation'));
            }
            return redirect()
                ->back()
                ->withErrors(__('crud.general.not_done'));
        }

        return redirect()
            ->back()
            ->withSuccess(__('crud.general.deleted'));
    }
}

app/Http/Controllers/User/ServiceController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\GeoFencing;
use App\Models\ServiceType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ServiceController extends Controller
{
    public function serviceCheckout(Request $request, GeoFencing $geoFence, ServiceType $serviceType)
    {
        // 
        return view('user.serviceCheckout');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.users.create') }}
@endsection

@section('heading')
    {{ __('crud.admin.users.create') }}
@endsection

@section('content')
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <x-form action="{{ route('admin.user.store') }}" method="post" has-file>
                @include('admin.user.form-inputs')
                
                <div class="flex justify-end">
                    <button type="submit" class="right-0 inline-block py-1 px-4 leading-loose bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg transition duration-200 text-sm" type="submit">Add User</button>
                </div>
            </x-form>
        </div>
    </div>
@endsection

@include('components.telephoneImport')

resources/views/admin/user/edit.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.users.update') }}
@endsection

@section('heading')
    {{ __('crud.admin.users.update') }}
@endsection

@section('content')
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <x-form action="{{ route('admin.user.update', $user) }}" method="put" has-file>
                @include('admin.user.form-inputs')
                
                <div class="flex justify-end">
                    <button type="submit" class="right-0 inline-block py-1 px-4 leading-loose bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg transition duration-200 text-sm" type="submit">Submit</button>
                </div>
            </x-form>
        </div>
    </div>
@endsection

@include('components.telephoneImport')

resources/views/admin/user/form-inputs.blade.php
@php 
    $editing = isset($user);
@endphp

<div class="flex flex-wrap -mx-4 -mb-4 md:mb-0">
    <x-inputs.text name="first_name" :label="__('crud.inputs.first_name')" value="{{ old('first_name', ($editing ? $user->first_name : '')) }}"></x-inputs.text>

    <x-inputs.text name="last_name" :label="__('crud.inputs.last_name')" value="{{ old('last_name', ($editing ? $user->last_name : '')) }}"></x-inputs.text>

    <x-inputs.email name="email" :label="__('crud.inputs.email')" value="{{ old('email', ($editing ? $user->email : '')) }}"></x-inputs.email>

    <div class="w-full md:w-1/2 px-4 mb-4 md:mb-0">
        <div class="mb-6">
            <input class="hidden" type="text" id="countryCode" name="country_code">
            <x-inputs.partials.label name="phone" :label="__('crud.inputs.phone')"></x-inputs.partials.label>
            <input type="tel" class="appearance-none w-full p-4 text-xs font-semibold leading-none dark:bg-gray-700 dark:text-gray-300 bg-gray-50 rounded outline-none mb-2 inptFielsd" id="phone" value="{{ old('country_code', ($editing && $user->country_code ? '+'.$user->country_code : '')) }}{{ old('mobile', ($editing && $user->mobile ? $user->mobile : '')) }}" placeholder="123456789" onfocusout="myFunction()" />
        </div>
    </div>
    
    @if(!$editing)
        <x-inputs.password name="password" :label="__('crud.inputs.password')" value="{{ old('password', ($editing ? $user->password : '')) }}"></x-inputs.password>
    @endif
    
    <div class="w-full md:w-1/2 px-4 mb-4 md:mb-0">
        <div class="mb-6">
            <div x-data="avatarComponentData()">
                <x-inputs.partials.label name="avatar" :label="__('crud.inputs.avatar')"></x-inputs.partials.label>
                <img :src="avatarDataUrl" style="object-fit: cover; width: 150px; height: 150px;"/><br />

                <div class="mt-2">
                    <input
                        class="block dark:text-gray-400 text-gray-800 text-sm font-semibold mb-2"
                        type="file"
                        name="avatar"
                        id="avatar"
                        @change="fileChanged"
                    />
                </div>
            </div>
        </div>
    </div>
</div>

@push('endScripts')
    <script>
        /* Alpine component for avatar uploader viewer */
        function avatarComponentData() {
            return {
                avatarDataUrl: '{{ $editing && $user->avatar ? asset("storage/".$user->avatar) : asset("img/avatar.png") }}',

                fileChanged(event) {
                    this.fileToDataUrl(event, src => this.avatarDataUrl = src)
                },

                fileToDataUrl(event, callback) {
                    if (! event.target.files.length) return

                    let file = event.target.files[0],
                        reader = new FileReader()

                    reader.readAsDataURL(file)
                    reader.onload = e => callback(e.target.result)
                }
            }
        }
    </script>
@endpush

resources/views/admin/user/index.blade.php
@extends('admin.layout.app')

@section('title')
Admin - {{ __('crud.admin.users.index') }}
@endsection

@section('heading')
{{ __('crud.admin.users.index') }}
@endsection

@section('content')
<x-indexPageSearch :addBtnRoute="route('admin.user.create')" :addBtnText="__('crud.admin.users.create')">
</x-indexPageSearch>
<div class="w-full overflow-hidden rounded-lg shadow-xs mb-6">
    <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
            <thead>
                <tr
                    class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                    <th class="text-center px-4 py-3">{{ __('crud.inputs.SNo') }}</th>
                    <th class="text-center px-4 py-3">{{ __('crud.admin.users.name') }} {{ __('crud.general.id') }}</th>
                    <th class="text-center px-4 py-3">{{ __('crud.inputs.name') }}</th>
                    <th class="text-center px-4 py-3">{{ __('crud.inputs.email') }}</th>
                    <th class="text-center px-4 py-3">{{ __('crud.inputs.phone') }}</th>
                    <th class="text-center px-4 py-3">{{ __('crud.general.wallet') }}</th>
                    <th class="text-center px-4 py-3">{{ __('crud.general.user') }} {{ __('crud.navlinks.request') }}
                    </th>
                    <th class="text-center px-4 py-3">{{ __('crud.general.actions') }}</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                {{-- Approved --}}
                @forelse ($users as $user)
                <tr class="text-gray-700 dark:text-gray-400">
                    <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3">{{ $loop->index + 1 }}</td>
                    <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3">{{ $user->id }}</td>
                    <td class="px-4 dark:text-gray-400 dark:bg-gray-800 py-3">
                        <div class="flex items-center text-sm">
                            <!-- Avatar with inset shadow -->
                            <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                                <img class="object-cover w-full h-full rounded-full"
                                    src="{{ $user->avatar ? asset('storage/'.$user->avatar) : "https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjE3Nzg0fQ" }}"
                                    alt="" loading="lazy" />
                                <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
                            </div>
                            <div>
                                <p class="font-semibold text-gray-700 dark:text-gray-400">{{ $user->name }}</p>
                                {{-- <p class="text-xs text-gray-600 dark:text-gray-400">
                                        10x Developer
                                        </p> --}}
                            </div>
                        </div>
                    </td>
                    <td class="px-4 dark:text-gray-400 dark:bg-gray-800 py-3 text-sm">
                        {{ $user->email ?? ''}}
                    </td>
                    <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3 text-sm">
                        {{ $user->country_code ? $user->country_code.'-' : '' }}{{ $user->mobile ?? ''}}
                    </td>
                    <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3 text-sm">
                        {{ currency($user->wallet_balance) ?? ''}}
                    </td>
                    <td class="text-center dark:text-gray-400 dark:bg-gray-800 px-4 py-3 text-sm">
                        {{ $user->userRequest->count() }}
                    </td>
                    <td>
                        <div class="flex items-center justify-center">
                            {{-- <x-buttons.show :link="route('admin.user.show', $user)"></x-buttons.show> --}}
                            <x-buttons.edit :link="route('admin.user.edit', $user)"></x-buttons.edit>
                            <x-buttons.delete :link="route('admin.user.destroy', $user)"></x-buttons.delete>
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td class="text-center dark:text-gray-400 dark:bg-gray-800 py-3 text-sm" colspan="10">
                        @lang('crud.general.not_found')
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    {{-- Pagination --}}
    <div class="">
        {!! $users->links() !!}
    </div>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layout.app')

@section('title')
    Admin - {{ __('crud.admin.users.show') }}
@endsection

@section('content')
    <div class="w-full rounded-lg shadow-xs bg-white dark:text-gray-400 dark:bg-gray-800 mb-5">
        <div class="w-full px-5 py-5">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ route('admin.user.index') }}" class="mr-2"><i class="icon ion-md-arrow-back"></i></a>
                        {{ __('crud.admin.users.show') }}
                    </h4>
    
                    <div class="mt-4 row">
                        <div class="col-lg-4 col-md-12">
                            <div class="text-center">
                                <img class="my-3" src="{{ $user->avatar ? asset('storage/'.$user->avatar) : asset('img/avatar.png') }}" style="object-fit: cover; width: 150px; height: 150px; border: 1px solid #ccc; border-radius: 50%;" />
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12 d-flex align-items-center">
                            <table wire:loading.remove wire:target="editMode" style="width: 100%;">
                                <tr class="view_td_container">
                                    <td class="view_td key">@lang('crud.admin.users.name')</td>
                                    <td class="view_td value">{{ $user->name ?? '-' }}</td>
                                    <td class="view_td key">@lang('crud.admin.users.email')</td>
                                    <td class="view_td value">{{ $user->email ?? '-' }}</td>
                                </tr>
                                <tr class="view_td_container">
                                    <td class="view_td key">@lang('crud.admin.users.phone')</td>
                                    <td class="view_td value">{{ $user->phone ?? '-' }}</td>
                                    <td class="view_td key">@lang('crud.roles.name')</td>
                                    <td class="view_td value">
                                        hdo
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection